### ISSUE TITLE
Connection "default" is not defined during Magento installation

### ISSUE THREAD

**Issue by ozkrpp** [zepgram/magento2-fast-vm#30]
Got this error during installation:
![image](https://user-images.githubusercontent.com/13484160/63485217-0cafc700-c468-11e9-85bb-b7cc53e3ff63.png)

This is the content of my config.yaml (unchanged from original except for Magento credentials):
vmconf:
  machine_name: 'Vagrant Magento 2'
  network_ip: '192.168.200.50'
  host_name: 'zepgram'
  memory: '4096'
  cpus: '1'
  mount: 'nfs'
  path: 'root'
  provision: 'all'
composer:
  username: 'removed'
  password: 'removed'
git:
  name: 'John Doe'
  email: 'john@doe.com'
  host: 'github.com'
  repository: 'ssh://git@github.com:project-name.git'
magento:
  url: 'dev.magento.com'
  source: 'composer'
  edition: 'community'
  version: '2.3.2'
  php_version: 'default'
  sample: 'true'
  mode: 'developer'
  currency: 'USD'
  language: 'en_US'
  time_zone: 'America/New_York'

**Comment by zepgram** [comment]
Hi ozkrpp,

It looks like it's related to opcache: https://github.com/magento/magento2/issues/22198
Did you destroy your vagrant after your change in config.yaml ?

Otherwise you can disable opcache in this file:
https://github.com/zepgram/magento2-fast-vm/blob/ef3c11ea8e8a58b12d1f49672bf0f110797aad45/provision/020-system-services.sh#L129

I'll investigate on my side to find out what happened.
