### ISSUE TITLE
Magento nginx docroot location

### ISSUE THREAD

**Issue by Vikwip** [zepgram/magento2-fast-vm#49]
Hello zepgram,

I don't understand how the nginx docroot is configured on my machine.
When I type the name of my server or ip address in the browser I just have the Nginx homepage displayed for now.
If I search in the browser for exisiting sub-folders in my home magento directory I get 404 errors.

How do I make it link to the cd directory /home/vagrant/magento/?

Thanks!

**Comment by zepgram** [comment]
If you have only the nginx page, it's because Magento directory mount
failed.
If you installed Magento through rsync, it's very important to wait the
rsync back to be done.
Or run the command right after the installation to send back your files
from guest to host machine.

**Comment by Vikwip** [comment]
Okay, thanks for your answer. I actually installed Magento through default mount, but it didn't work because of [the composer error](https://github.com/zepgram/magento2-fast-vm/issues/48).

I'm trying to install it manually now.

In this case do I need at worst to reinstall my virtual machine, or else just run a ` vagrant rsync-back` command, or eventually trying to modify nginx.conf file?

**Comment by zepgram** [comment]
The process to get it work correctly would be:
1. set config mount to "rsync" (this way you should avoid the manual composer install)
1. wait for the rsync-back to be done completely
1. stop your machine with `vagrant halt`
1. set config mount to "default" then restart vagrant with `vagrant up`

Check your repository /home/vagrant/magento with `vagrant ssh` if it's again empty, tell me and we'll find an other process.

nginx conf is fine: your repository /home/vagrant/magento is symlinked to /var/www/magento, if you just have the nginx page it's because the mount failed.

**Comment by zepgram** [comment]
Note: rsync-back is only required when mount option is "rsync" and when you generate files from guest machine.

**Comment by Vikwip** [comment]
Hi zepgram,

In fact my /home/vagrant/magento directory is not empty.
There was already a directory that I cloned from github.
By the way, when I start the machine with rsync mount nothing happens on the first window, even after 10 minutes. Is that normal?:

`==> zepgram: >>> Do not close this terminal: open new one for ssh login
==> zepgram: ---------------------------------------------------------
==> zepgram: rsync-back and rsync auto triggered...
==> zepgram: Duration: ~10min. Install is done when rsync-auto will start watching.
    zepgram: Running local: Inline script
    zepgram: vagrant rsync-back zepgram | vagrant rsync-auto --rsync-chown zepgram
    zepgram: ==> zepgram: Doing an initial rsync...
    zepgram: ==> zepgram: Rsyncing folder: /cygdrive/c/Users/user/magento2-fast-vm/www/magento/ => /home/vagrant/magento
    zepgram: ==> zepgram:   - Exclude: [".vagrant/", "generated/code/*", "var/page_cache/*", "var/view_preprocessed/*", "pub/static/adminhtml/*", "pub/static/base/*", "pub/static/frontend/*", "dev", "node_modules", "phpserver", "setup", "update"]
    zepgram: ==> zepgram: Watching: C:/Users/user/magento2-fast-vm/www/magento`

**Comment by zepgram** [comment]
If you use rsync mount the process for transferring files between host and guest is not conventional.
First rsync is single directional, and transfer are made from host to guest with **rsync-auto**.
The rsync-auto is launched automatically on vagrant up: this will allow a watcher to do files transfers the terminal must be kept open in order to transfer files correctly.
If you modify any file from your most machine, you'll see a new line on your terminal indicating that files have been transferred.

Then if you do any change under the guest machine (composer install for exemple) you must run **rsync-back** to get your files on host machine.
If you don't, on next startup, files will be erased by host machine.
So if your directory `/www/magento/vendor` is empty on host machine, the directory `/home/vagrant/magento/vendor` on guest will be empty on next vagrant up.

**Comment by Vikwip** [comment]
Hi zepagram,
Thanks again for your advices and your explanations.
I finally created an additional virtualhost in my nginx configuration file. Then I linked it to my magento installation folder.
