### ISSUE TITLE
Bitbucket clone

### ISSUE THREAD

**Issue by marcelaerts** [zepgram/magento2-fast-vm#5]
Is there a way to clone a repo from bitbucket? It tried by changing the credentials but I'm getting an error with vagrant up?

ssh: Could not resolve hostname bitbucket.org:

**Comment by zepgram** [comment]
I never tried from bitbucket.
Did you change value in config.yaml for credentials: "git_host" ?
```
credentials:
  git_host: 'bitbucket.org'
```
This will add host key in guest machine, this way clone can be done without interaction.

Otherwise, according to Atlassian I will try this for url repository:
**git@bitbucket.org:teamsinspace/documentation-tests.git**
and
**ssh://git@bitbucket.org:teamsinspace/documentation-tests.git**

**Comment by marcelaerts** [comment]
Yes I tried by changing the git_host.

**Comment by Bwilliamson55** [comment]
I know this issue is closed, but I wanted to drop a note here for other people. 
`  host: 'bitbucket.org'
  repository: 'git@bitbucket.org:{user}/{reponame}.git'`
Worked for me.
